on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: "custom ref"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request'

      - name: Checkout PR
        uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: github.event.inputs.ref

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -o main
