name: PR Comment Command

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  e2e:
    uses: tuunit/e2e-repo/.github/workflows/e2e.yml@main
