name: PR Comment Command

on:
  issue_comment:
    types: [created]

jobs:
  e2e:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
    if: |
      github.event.issue.pull_request && 
      (github.event.comment.author_association == 'MEMBER' ||
       github.event.comment.author_association == 'OWNER') &&
      startsWith(github.event.comment.body, '/e2e')
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Print full PR object
        run: |
          echo "Full PR object:"
          echo '${{ toJSON(github.event.issue.pull_request) }}'
          echo ""
          echo "GitHub context:"
          echo '${{ toJSON(github) }}'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -o main

      - name: Parse comment
        id: parse-comment
        run: |
          COMMENT="${{ github.event.comment.body }}"
          if [[ "$COMMENT" == "/e2e PR-"* ]]; then
            PR_NUMBER=${COMMENT//[!0-9]/}
            echo "mode=pr" >> $GITHUB_OUTPUT
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          elif [[ "$COMMENT" == "/e2e "* ]]; then
            BRANCH=${COMMENT#/e2e }
            echo "mode=branch" >> $GITHUB_OUTPUT
            echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          else
            echo "mode=default" >> $GITHUB_OUTPUT
          fi

      - name: Checkout e2e repo (main)
        if: steps.parse-comment.outputs.mode == 'default'
        run: |
          git clone https://github.com/tuunit/e2e-repo.git

      - name: Checkout e2e repo (branch)
        if: steps.parse-comment.outputs.mode == 'branch'
        run: |
          git clone --branch ${{ steps.parse-comment.outputs.branch }} \
            https://github.com/tuunit/e2e-repo.git

      - name: Clone e2e repo (PR)
        if: steps.parse-comment.outputs.mode == 'pr'
        run: |
          git clone https://github.com/tuunit/e2e-repo.git
          cd e2e-repo
          git fetch origin pull/${{ steps.parse-comment.outputs.pr_number }}/head:pr-${{ steps.parse-comment.outputs.pr_number }}
          git checkout pr-${{ steps.parse-comment.outputs.pr_number }}

      - name: E2E Testing
        run: ./e2e-repo/test.sh
